const ADD_MOVIE = 'ADD_MOVIE';
const DELETE_MOVIE = 'DELETE_MOVIE';
const FILTER_FILM_LIST = 'FILTER_FILM_LIST';
const CHANGE_TERM = 'CHANGE_TERM';
const CHANGE_IS_OPEN = 'CHANGE_IS_OPEN';
const CHANGE_NEW_ELEMENT_TITLE = 'CHANGE_NEW_ELEMENT_TITLE';
const CHANGE_NEW_ELEMENT_RELEASE_YEAR = 'CHANGE_NEW_ELEMENT_RELEASE_YEAR';
const CHANGE_NEW_ELEMENT_FORMAT = 'CHANGE_NEW_ELEMENT_FORMAT';
const CHANGE_NEW_ELEMENT_STARS = 'CHANGE_NEW_ELEMENT_STARS';
const CLEAR_NEW_ITEM = 'CLEAR_NEW_ITEM';
const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
const SORT = 'SORT';

export {
  ADD_MOVIE,
  DELETE_MOVIE,
  FILTER_FILM_LIST,
  CHANGE_TERM,
  CHANGE_IS_OPEN,
  CHANGE_NEW_ELEMENT_TITLE,
  CHANGE_NEW_ELEMENT_RELEASE_YEAR,
  CHANGE_NEW_ELEMENT_FORMAT,
  CHANGE_NEW_ELEMENT_STARS,
  CLEAR_NEW_ITEM,
  ADD_NEW_ITEM,
  SORT
};
